/**
 * NOOR copy — Arabic-first, feminine, beauty-oriented.
 *
 * NOOR reuses the shared, security-reviewed `SouqCopy` contract (the order
 * form, variants and success flows all read from it) and overrides the
 * storefront voice with a soft premium beauty tone. French / English keep the
 * shared fallback copy, exactly like the other V2 templates.
 */
import { souqCopy, type SouqCopy } from "../souq/copy";
import type { StoreLanguage } from "../../types";

export function noorCopy(lang?: StoreLanguage | string | null): SouqCopy {
  const base = souqCopy(lang);
  if (lang === "fr" || lang === "en") return base;
  return {
    ...base,
    promo: {
      ...base.promo,
      defaultBar: "توصيل إلى 58 ولاية • الدفع عند الاستلام",
      delivery: "توصيل إلى 58 ولاية",
      cod: "الدفع عند الاستلام",
    },
    nav: {
      ...base.nav,
      home: "الرئيسية",
      shop: "المتجر",
      categories: "تسوّقي حسب الفئة",
      offers: "العروض",
      bestSellers: "الأكثر مبيعاً",
      newArrivals: "وصل حديثاً",
      about: "من نحن",
      contact: "تواصلي معنا",
      faq: "الأسئلة الشائعة",
    },
    search: {
      ...base.search,
      placeholder: "ابحثي عن منتج...",
      open: "ابحثي عن منتج",
      noResults: "لا نتائج مطابقة",
      noResultsHint: "جرّبي كلمة أخرى أو تصفّحي الفئات.",
      viewAll: "عرض كل النتائج",
    },
    hero: {
      ...base.hero,
      badge: "عناية مختارة بعناية",
      ctaFallback: "اكتشفي المجموعة",
      browseCategories: "تسوّقي حسب الفئة",
      trustDelivery: "توصيل إلى 58 ولاية",
      trustCod: "الدفع عند الاستلام",
      trustSpeed: "تأكيد سريع للطلب",
    },
    sections: {
      ...base.sections,
      categoriesTitle: "تسوّقي حسب الفئة",
      categoriesSubtitle: "كل ما تحتاجينه لبشرتكِ وشعركِ وعطركِ",
      trendingTitle: "مختارات نور",
      trendingSubtitle: "قطع أساسية لعناية يومية متوازنة",
      flashTitle: "عروض خاصة",
      flashSubtitle: "وفّري أكثر عند اختيار الكمية",
      bestTitle: "الأكثر مبيعاً",
      bestSubtitle: "اختيارات محبوبة من عميلاتنا",
      newTitle: "وصل حديثاً",
      newSubtitle: "منتجات جديدة اختيرت بعناية",
      whyTitle: "لماذا نور؟",
      whySubtitle: "تجربة عناية بكل ثقة وطمأنينة",
      reviewsTitle: "قالوا عن نور",
      reviewsSubtitle: "آراء منشورة من عميلات المتجر",
      faqTitle: "أسئلة تتكرر",
      faqSubtitle: "إجابات من إعداد المتجر قبل إتمام طلبكِ",
      contactTitle: "نحن هنا لمساعدتكِ",
      noProducts: "لا منتجات بعد",
      noProductsHint: "ستظهر المنتجات هنا فور إضافتها من لوحة التحكم.",
      viewAll: "شاهدي الكل",
      offerBadge: "عرض خاص",
      offerNote: "تظهر العروض المتاحة والسعر النهائي داخل صفحة المنتج.",
    },
    product: {
      ...base.product,
      breadcrumbHome: "الرئيسية",
      breadcrumbShop: "المتجر",
      bestSeller: "الأكثر مبيعاً",
      newBadge: "جديد",
      specialOffer: "عرض خاص",
      inStock: "متوفر",
      lowStock: "كمية محدودة",
      outOfStock: "غير متوفر حالياً",
      chooseOptions: "اختاري المواصفات",
      quantity: "الكمية",
      quantityOffers: "عروض الكمية",
      mostOrdered: "الأكثر اختياراً",
      singleUnit: "قطعة واحدة",
      twoUnits: "قطعتان",
      nUnits: "{n} قطع",
      save: "وفّري",
      description: "الوصف",
      features: "الفوائد",
      related: "قد يعجبكِ أيضاً",
      faq: "أسئلة شائعة",
      gallery: "معرض الصور",
      orderNow: "اطلبي الآن",
      addToCart: "أضيفي إلى الطلب",
      whatsappAsk: "اسألي على واتساب",
      callAsk: "اتصلي بنا",
      backToShop: "العودة إلى المتجر",
      notAvailable: "غير متوفر",
      codPayment: "الدفع عند الاستلام",
      deliveryHome: "إلى المنزل",
      deliveryOffice: "إلى المكتب",
      secureOrder: "طلب آمن",
      customerService: "خدمة الزبائن",
      deliveryTo58: "توصيل إلى 58 ولاية",
    },
    checkout: {
      ...base.checkout,
      formTitle: "أكملي طلبك",
      formSubtitle: "أدخلي معلوماتك وسنتواصل معك لتأكيد الطلب",
      firstName: "الاسم",
      lastName: "اللقب",
      firstNamePlaceholder: "مثال: نور",
      lastNamePlaceholder: "مثال: بن يوسف",
      phone: "رقم الهاتف",
      phonePlaceholder: "05 XX XX XX XX",
      phoneHint: "سنتواصل معكِ على هذا الرقم لتأكيد الطلب",
      wilaya: "الولاية",
      wilayaPlaceholder: "اختاري الولاية",
      commune: "البلدية",
      communePlaceholder: "اختاري البلدية",
      deliveryMethod: "طريقة التوصيل",
      home: "إلى المنزل",
      office: "إلى المكتب",
      address: "العنوان",
      addressPlaceholder: "الحي، الشارع، رقم المنزل",
      officeName: "مكتب التوصيل",
      officePlaceholder: "اسم مكتب التوصيل الأقرب إليكِ",
      summary: "ملخص الطلب",
      products: "سعر المنتجات",
      shipping: "التوصيل",
      shippingFree: "مجاني",
      shippingPending: "يُحدَّد بعد اختيار الولاية",
      discount: "الخصم",
      total: "المجموع",
      submit: "تأكيد الطلب",
      submitting: "جارٍ الإرسال...",
      codNote: "الدفع عند الاستلام",
      secureNote: "السعر النهائي يُعاد احتسابه بأمان عند إرسال الطلب",
    },
    success: {
      ...base.success,
      title: "تم استلام طلبكِ",
      subtitle: "سنتواصل معكِ لتأكيد التفاصيل قبل الإرسال.",
      backToShop: "تابعي التسوق",
    },
    errors: {
      ...base.errors,
      firstName: "أدخلي الاسم",
      lastName: "أدخلي اللقب",
      phone: "أدخلي رقم هاتف صحيح",
      phoneMobile: "أدخلي رقم هاتف جزائري صحيح",
      wilaya: "اختاري الولاية",
      commune: "اختاري البلدية",
      address: "أدخلي العنوان",
      office: "أدخلي مكتب التوصيل",
    },
    footer: {
      ...base.footer,
      aboutFallback: "منتجات عناية وتجميل مختارة بعناية لبشرة أكثر نعومة ونضارة.",
      navigation: "روابط سريعة",
      contact: "تواصلي معنا",
      policies: "سياسات",
      terms: "الشروط العامة",
      privacy: "سياسة الخصوصية",
      faq: "الأسئلة الشائعة",
      copyright: "جميع الحقوق محفوظة",
      codLine: "الدفع عند الاستلام • توصيل إلى 58 ولاية",
    },
  };
}
